// Copyright 2024 Tommaso Visconti (@tommyblue)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

/* Handedness. */
#define MASTER_RIGHT

/* Reset. */
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

/* SPI & PMW3360 settings. */
#define SPI_DRIVER SPID0
#define SPI_SCK_PIN GP22
#define SPI_MISO_PIN GP20
#define SPI_MOSI_PIN GP23
#define POINTING_DEVICE_CS_PIN GP21
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
// #define POINTING_DEVICE_DEBUG
#define SPLIT_LAYER_STATE_ENABLE

#define MATRIX_ROWS 8
#define MATRIX_COLS 6
#define MATRIX_COL_PINS { GP2, GP3, GP4, GP5, GP6, GP7 }
#define MATRIX_ROW_PINS { GP8, GP9, GP12, GP13 }
#define MATRIX_COL_PINS_RIGHT { GP2, GP3, GP4, GP5, GP6, GP7 }
#define MATRIX_ROW_PINS_RIGHT { GP8, GP9, GP12, GP13 }

#define ROTATIONAL_TRANSFORM_ANGLE -25
#define POINTING_DEVICE_INVERT_X
// #define POINTING_DEVICE_INVERT_Y


#ifdef POINTING_DEVICE_ENABLE
    #define PMW33XX_CPI 1000

// Add MOUSE_EXTENDED_REPORT by default
#    ifndef FP_POINTING_EXTENDED_MOUSE_REPORT_DISABLE
#        define MOUSE_EXTENDED_REPORT
#    endif

#    ifndef FP_POINTING_DEFAULT_DPI
#        define FP_POINTING_DEFAULT_DPI 10
#    endif

#    ifndef FP_POINTING_MIN_DPI
#        define FP_POINTING_MIN_DPI 2
#    endif

#    ifndef FP_POINTING_MAX_DPI
#        define FP_POINTING_MAX_DPI 60
#    endif

#    ifndef FP_POINTING_SNIPING_DPI
#        define FP_POINTING_SNIPING_DPI 2
#    endif

#    ifndef FP_POINTING_SNIPING_LAYER
#        define FP_POINTING_SNIPING_LAYER 2
#    endif

#    ifndef FP_POINTING_SNIPING_MIN_DPI
#        define FP_POINTING_SNIPING_MIN_DPI 2
#    endif

#    ifndef FP_POINTING_SNIPING_MAX_DPI
#        define FP_POINTING_SNIPING_MAX_DPI 5
#    endif

#    ifndef FP_POINTING_SCROLLING_DPI
#        define FP_POINTING_SCROLLING_DPI 2
#    endif

#    ifndef FP_POINTING_SCROLLING_LAYER
#        define FP_POINTING_SCROLLING_LAYER 3
#    endif

#    ifndef FP_POINTING_SCROLLING_MIN_DPI
#        define FP_POINTING_SCROLLING_MIN_DPI 2
#    endif

#    ifndef FP_POINTING_SCROLLING_MAX_DPI
#        define FP_POINTING_SCROLLING_MAX_DPI 10
#    endif

#    ifndef FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY
#        define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY 3
#    endif

#    ifndef FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY_X
#        define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY_X FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY
#    endif

#    ifndef FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY_Y
#        define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY_Y FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY
#    endif

#    ifndef FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY_H
#        define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY_H FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY
#    endif

#    ifndef FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY_V
#        define FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY_V FP_AUTO_MOUSE_TRACKBALL_SENSITIVITY
#    endif

#    ifndef FP_POINTING_ZOOMING_LAYER
#        define FP_POINTING_ZOOMING_LAYER 1
#    endif

#endif
